// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjjHE3H7Su7lQ4d3u_l1OMx1QPpDCgS10',
    appId: '1:945213917724:web:a3b8494fcd19b31051edd9',
    messagingSenderId: '945213917724',
    projectId: 'quantova-ecd4f',
    authDomain: 'quantova-ecd4f.firebaseapp.com',
    storageBucket: 'quantova-ecd4f.firebasestorage.app',
    measurementId: 'G-YKEPGKY43D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD82-tOn0tnyakBC_cLvG6oz5VoAK8wHVc',
    appId: '1:945213917724:android:88f07e2cdf30e3f651edd9',
    messagingSenderId: '945213917724',
    projectId: 'quantova-ecd4f',
    storageBucket: 'quantova-ecd4f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHPbK000IDX4y636Etu8BSoh82SYrm_NM',
    appId: '1:945213917724:ios:a499177b9d4dc1f651edd9',
    messagingSenderId: '945213917724',
    projectId: 'quantova-ecd4f',
    storageBucket: 'quantova-ecd4f.firebasestorage.app',
    iosBundleId: 'com.example.gastosMensualesNew',
  );

}