// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'core/database/entities/category.dart';
import 'core/database/entities/transaction.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 6744896488281043812),
    name: 'ExpenseTransaction',
    lastPropertyId: const obx_int.IdUid(8, 7390239013733025406),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 1132203336212714210),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 6296340779117077162),
        name: 'type',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 2655075188082972104),
        name: 'amount',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 5787788797776278881),
        name: 'date',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 2237691362017003896),
        name: 'description',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 6054042248144251359),
        name: 'category',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 2052274208194959966),
        name: 'receiptPath',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 7390239013733025406),
        name: 'categoryId',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 2219137024965685110),
    name: 'Category',
    lastPropertyId: const obx_int.IdUid(7, 2313466357996318390),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 9018647482455870130),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 3758809340553183982),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 6512956532128854948),
        name: 'iconName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 6333655749172092658),
        name: 'colorValue',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 3598723132321023550),
        name: 'isDefault',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 5500932810136101016),
        name: 'isActive',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 2313466357996318390),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    entities: _entities,
    lastEntityId: const obx_int.IdUid(2, 2219137024965685110),
    lastIndexId: const obx_int.IdUid(0, 0),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    ExpenseTransaction: obx_int.EntityDefinition<ExpenseTransaction>(
      model: _entities[0],
      toOneRelations: (ExpenseTransaction object) => [],
      toManyRelations: (ExpenseTransaction object) => {},
      getId: (ExpenseTransaction object) => object.id,
      setId: (ExpenseTransaction object, int id) {
        object.id = id;
      },
      objectToFB: (ExpenseTransaction object, fb.Builder fbb) {
        final descriptionOffset = object.description == null
            ? null
            : fbb.writeString(object.description!);
        final categoryOffset = object.category == null
            ? null
            : fbb.writeString(object.category!);
        final receiptPathOffset = object.receiptPath == null
            ? null
            : fbb.writeString(object.receiptPath!);
        fbb.startTable(9);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.type);
        fbb.addFloat64(2, object.amount);
        fbb.addInt64(3, object.date.millisecondsSinceEpoch);
        fbb.addOffset(4, descriptionOffset);
        fbb.addOffset(5, categoryOffset);
        fbb.addOffset(6, receiptPathOffset);
        fbb.addInt64(7, object.categoryId);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final typeParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        final amountParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        final dateParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0),
        );
        final descriptionParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 12);
        final categoryParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 14);
        final receiptPathParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 16);
        final categoryIdParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          18,
        );
        final object = ExpenseTransaction(
          id: idParam,
          type: typeParam,
          amount: amountParam,
          date: dateParam,
          description: descriptionParam,
          category: categoryParam,
          receiptPath: receiptPathParam,
          categoryId: categoryIdParam,
        );

        return object;
      },
    ),
    Category: obx_int.EntityDefinition<Category>(
      model: _entities[1],
      toOneRelations: (Category object) => [],
      toManyRelations: (Category object) => {},
      getId: (Category object) => object.id,
      setId: (Category object, int id) {
        object.id = id;
      },
      objectToFB: (Category object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        final iconNameOffset = fbb.writeString(object.iconName);
        fbb.startTable(8);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addOffset(2, iconNameOffset);
        fbb.addInt64(3, object.colorValue);
        fbb.addBool(4, object.isDefault);
        fbb.addBool(5, object.isActive);
        fbb.addInt64(6, object.createdAt.millisecondsSinceEpoch);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final iconNameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final colorValueParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final isDefaultParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          12,
          false,
        );
        final isActiveParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          14,
          false,
        );
        final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 16, 0),
        );
        final object = Category(
          id: idParam,
          name: nameParam,
          iconName: iconNameParam,
          colorValue: colorValueParam,
          isDefault: isDefaultParam,
          isActive: isActiveParam,
          createdAt: createdAtParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [ExpenseTransaction] entity fields to define ObjectBox queries.
class ExpenseTransaction_ {
  /// See [ExpenseTransaction.id].
  static final id = obx.QueryIntegerProperty<ExpenseTransaction>(
    _entities[0].properties[0],
  );

  /// See [ExpenseTransaction.type].
  static final type = obx.QueryIntegerProperty<ExpenseTransaction>(
    _entities[0].properties[1],
  );

  /// See [ExpenseTransaction.amount].
  static final amount = obx.QueryDoubleProperty<ExpenseTransaction>(
    _entities[0].properties[2],
  );

  /// See [ExpenseTransaction.date].
  static final date = obx.QueryDateProperty<ExpenseTransaction>(
    _entities[0].properties[3],
  );

  /// See [ExpenseTransaction.description].
  static final description = obx.QueryStringProperty<ExpenseTransaction>(
    _entities[0].properties[4],
  );

  /// See [ExpenseTransaction.category].
  static final category = obx.QueryStringProperty<ExpenseTransaction>(
    _entities[0].properties[5],
  );

  /// See [ExpenseTransaction.receiptPath].
  static final receiptPath = obx.QueryStringProperty<ExpenseTransaction>(
    _entities[0].properties[6],
  );

  /// See [ExpenseTransaction.categoryId].
  static final categoryId = obx.QueryIntegerProperty<ExpenseTransaction>(
    _entities[0].properties[7],
  );
}

/// [Category] entity fields to define ObjectBox queries.
class Category_ {
  /// See [Category.id].
  static final id = obx.QueryIntegerProperty<Category>(
    _entities[1].properties[0],
  );

  /// See [Category.name].
  static final name = obx.QueryStringProperty<Category>(
    _entities[1].properties[1],
  );

  /// See [Category.iconName].
  static final iconName = obx.QueryStringProperty<Category>(
    _entities[1].properties[2],
  );

  /// See [Category.colorValue].
  static final colorValue = obx.QueryIntegerProperty<Category>(
    _entities[1].properties[3],
  );

  /// See [Category.isDefault].
  static final isDefault = obx.QueryBooleanProperty<Category>(
    _entities[1].properties[4],
  );

  /// See [Category.isActive].
  static final isActive = obx.QueryBooleanProperty<Category>(
    _entities[1].properties[5],
  );

  /// See [Category.createdAt].
  static final createdAt = obx.QueryDateProperty<Category>(
    _entities[1].properties[6],
  );
}
